payment/urls.py
from django.urls import path
from .views import (
    PaymentView, EnrollView,
    CreateSubscriptionView, RetryInvoiceView,
    webhook,
   ChangeSubscriptionView
   )

app_name = "payment"

urlpatterns = [
    path('enroll/', EnrollView.as_view(), name='enroll'),
    path('enroll/<slug>/', PaymentView, name='payment'),
    path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
    path('change-subscription/', ChangeSubscriptionView.as_view(), name='change-subscription'),
    path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
    path('webhook/', webhook, name='webhook')
]

share/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token
from products.views import (
    ProductListView,
    UserProductListView,
    ProductCreateView,
    CreateCheckoutSessionView,
    SuccessView,
    stripe_webhook
)
from users.views import UserProfileView, StripeAccountLinkView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name="pages/base.html"), name="home"),
    path("users/", include("users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("discover/", ProductListView.as_view(), name='discover'),
    path('products/', UserProductListView.as_view(), name='user-products'),
    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path("create-checkout-session/<slug>/", CreateCheckoutSessionView.as_view(), name="create-checkout-session"),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('stripe/auth/', StripeAccountLinkView.as_view(), name='stripe-account-link'),
    path("p/", include('products.urls', namespace='products')),
    path('success/', SuccessView.as_view(), name='success'),
    path("webhooks/stripe/", stripe_webhook, name='stripe-webhook'),
]


# API URLS
urlpatterns += [
    # API base url
    path("api/", include("share.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import APIView
from rest_framework.response import Response
import stripe

from content.models import Pricing
User = get_user_model()
stripe.api_key = settings.STRIPE_SECRET_KEY



@csrf_exempt
def webhook(request):
    # You can use webhooks to receive information about asynchronous payment events.
    # For more about our webhook events check out https://stripe.com/docs/webhooks.
    webhook_secret = settings.STRIPE_WEBHOOK_SECRET
    payload = request.body

    # Retrieve the event by verifying the signature using the raw body and secret if webhook signing is configured.
    signature = request.META["HTTP_STRIPE_SIGNATURE"]
    try:
        event = stripe.Webhook.construct_event(
            payload=payload, sig_header=signature, secret=webhook_secret)
        data = event['data']
    except Exception as e:
        return e

    # Get the type of webhook event sent - used to check the status of PaymentIntents.
    event_type = event['type']
    data_object = data['object']

    if event_type == 'invoice.paid':
        # Used to provision services after the trial has ended.
        # The status of the invoice will show up as paid. Store the status in your
        # database to reference when a user accesses your service to avoid hitting rate
        # limits.
        # TODO: change the users subscription and pricing

        webhook_object = data["object"]
        stripe_customer_id = webhook_object["customer"]

        stripe_sub = stripe.Subscription.retrieve(webhook_object["subscription"])
        stripe_price_id = stripe_sub["plan"]["id"]

        pricing = Pricing.objects.get(stripe_price_id=stripe_price_id)

        user = User.objects.get(stripe_customer_id=stripe_customer_id)
        user.subscription.status = stripe_sub["status"]
        user.subscription.stripe_subscription_id = webhook_object["subscription"]
        user.subscription.pricing = pricing
        user.subscription.save()

    if event_type == 'invoice.finalized':
        # If you want to manually send out invoices to your customers
        # or store them locally to reference to avoid hitting Stripe rate limits.
        print(data)

    if event_type == 'customer.subscription.deleted':
        # handle subscription cancelled automatically based
        # upon your subscription settings. Or if the user cancels it.
        webhook_object = data["object"]
        stripe_customer_id = webhook_object["customer"]
        stripe_sub = stripe.Subscription.retrieve(webhook_object["id"])
        user = User.objects.get(stripe_customer_id=stripe_customer_id)
        user.subscription.status = stripe_sub["status"]
        user.subscription.save()

    if event_type == 'customer.subscription.trial_will_end':
        # Send notification to your user that the trial will end
        print(data)

    if event_type == 'customer.subscription.updated':
        print(data)

    return HttpResponse()

class EnrollView(generic.TemplateView):
    template_name = "payment/enroll.html"

def PaymentView(request, slug):
    subscription = request.user.subscription
    pricing = get_object_or_404(Pricing, slug=slug)

    if subscription.pricing == pricing and subscription.is_active:
        messages.info(request, "You are already enrolled for this package")
        return redirect("payment:enroll")

    context = {
        "pricing_tier": pricing,
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
    }

    if subscription.is_active and subscription.pricing.stripe_price_id != "free-trial":
        return render(request, "payment/change.html", context)

    return render(request, "payment/checkout.html", context)


class CreateSubscriptionView(APIView):
    def post(self, request, *args, **kwargs):
        data = request.data
        customer_id = request.user.stripe_customer_id
        try:
            # Attach the payment method to the customer
            stripe.PaymentMethod.attach(
                data['paymentMethodId'],
                customer=customer_id,
            )
            # Set the default payment method on the customer
            stripe.Customer.modify(
                customer_id,
                invoice_settings={
                    'default_payment_method': data['paymentMethodId'],
                },
            )

            # Create the subscription
            subscription = stripe.Subscription.create(
                customer=customer_id,
                items=[{'price': data["priceId"].strip()}],
                expand=['latest_invoice.payment_intent'],
            )

            data = {}
            data.update(subscription)

            return Response(data)
        except Exception as e:
            return Response({
                "error": {'message': str(e)}
            })




class RetryInvoiceView(APIView):
    def post(self, request, *args, **kwargs):
        data = request.data
        customer_id = request.user.stripe_customer_id
        try:

            stripe.PaymentMethod.attach(
                data['paymentMethodId'],
                customer=customer_id,
            )
            # Set the default payment method on the customer
            stripe.Customer.modify(
                customer_id,
                invoice_settings={
                    'default_payment_method': data['paymentMethodId'],
                },
            )

            invoice = stripe.Invoice.retrieve(
                data['invoiceId'],
                expand=['payment_intent'],
            )
            data = {}
            data.update(invoice)

            return Response(data)
        except Exception as e:

            return Response({
                "error": {'message': str(e)}
            })


class ChangeSubscriptionView(APIView):
    def post(self, request, *args, **kwargs):
        print(request.data)
        subscription_id = request.user.subscription.stripe_subscription_id
        subscription = stripe.Subscription.retrieve(subscription_id)
        try:
            updatedSubscription = stripe.Subscription.modify(
                subscription_id,
                cancel_at_period_end=False,
                items=[{
                    'id': subscription['items']['data'][0].id,
                    'price': request.data["priceId"].strip(),
                }],
                proration_behavior="always_invoice"
            )

            data = {}
            data.update(updatedSubscription)
            return Response(data)
        except Exception as e:
            return Response({
                "error": {'message': str(e)}
            })

templates/payment/change.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/stripe.css' %}" />

{% endblock extra_head %}

{% block content %}
  <div class="flex justify-center mx-auto">
    <div class="py-3">
      <div class="border border-gray-200 rounded shadow-md px-3 py-3">
        <h2 class="text-xl text-center text-gray-500">
          Get the {{ pricing_tier.name }} Package
        </h2>
        <p class="text-3xl text-center text-gray-800">
          {% if pricing_tier.currency != "usd" %}
          ${{ pricing_tier.price }}/mo
          {% else %}
          €{{ pricing_tier.price }}/mo
          {% endif %}
        </p>
      </div>
      <div class="mt-3">
        <form id="change-form">
          {% csrf_token %}
          <button id="submit" type="submit">
              <div class="spinner hidden" id="spinner"></div>
              <span id="button-text">Pay</span>
          </button>
      
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
<script>

const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

function updateSubscription(priceId, subscriptionId) {
  return fetch("{% url 'payment:change-subscription' %}", {
    method: 'post',
    headers: {
      'Content-type': 'application/json',
      'X-CSRFToken': csrftoken
    },
    body: JSON.stringify({
      priceId: "{{ pricing_tier.stripe_price_id }}",
    }),
  })
    .then(response => {
      return response.json();
    })
    .then(response => {
      window.location.href = "{% url 'users:subscription' request.user.username %}"
      return response;
    });
}

function changeLoadingState(isLoading) {
  if (isLoading) {
    document.querySelector('#button-text').classList.add('hidden');
    document.querySelector('#spinner').classList.remove('hidden');
    document.querySelector('#change-form button').disabled = true;
  } else {
    document.querySelector('#button-text').classList.remove('hidden');
    document.querySelector('#spinner').classList.add('hidden');
    document.querySelector('#change-form button').disabled = false;
  }
}

var form = document.getElementById('change-form');

form.addEventListener('submit', function (ev) {
  ev.preventDefault();
  changeLoadingState(true);
  updateSubscription()
});

</script>
{% endblock javascript %}

templates/payment/checkout.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/stripe.css' %}" />
<script src="https://js.stripe.com/v3/"></script>
{% endblock extra_head %}

{% block content %}
  <div class="flex justify-center mx-auto">
    <div class="py-3">
      <div class="border border-purple-200 rounded shadow-md px-3 py-3">
        <h2 class="text-xl text-center text-gray-100">
          Enroll for the {{ pricing_tier.name }} membership
        </h2>
        <p class="text-3xl text-center text-gray-800">
          {% if pricing_tier.currency == "usd" %}
          ${{ pricing_tier.price }}/mo
          {% else %}
          €{{ pricing_tier.price }}/mo
          {% endif %}
        </p>
      </div>
      <div class="mt-3">

        <form id="subscription-form">
          {% csrf_token %}
          <div id="card-element"><!--Stripe.js injects the Card Element--></div>
          <button class="btn" id="submit" type="submit">
              <div class="spinner hidden" id="spinner"></div>

              <span id="button-text">Pay</span>
          </button>

          <p id="card-errors" role="alert"></p>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
<script>

const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
var elements = stripe.elements();

// Set up Stripe.js and Elements to use in checkout form
var style = {
  base: {
    color: "#32325d",
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: "antialiased",
    fontSize: "16px",
    "::placeholder": {
      color: "#aab7c4"
    }
  },
  invalid: {
    color: "#fa755a",
    iconColor: "#fa755a"
  }
};

var priceId = "{{ pricing_tier.stripe_price_id }}"

var card = elements.create("card", { style: style });
card.mount("#card-element");

card.on('change', showCardError);

function showCardError(event) {
  let displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
}

var form = document.getElementById('subscription-form');

form.addEventListener('submit', function (ev) {
  ev.preventDefault();
  changeLoadingState(true);

  // If a previous payment was attempted, get the latest invoice
  const latestInvoicePaymentIntentStatus = localStorage.getItem(
    'latestInvoicePaymentIntentStatus'
  );

  if (latestInvoicePaymentIntentStatus === 'requires_payment_method') {
    const invoiceId = localStorage.getItem('latestInvoiceId');
    const isPaymentRetry = true;
    // create new payment method & retry payment on invoice with new payment method
    createPaymentMethod({
      card,
      isPaymentRetry,
      invoiceId,
    });
  } else {
    // create new payment method & create subscription
    createPaymentMethod({ card });
  }
});


function createPaymentMethod({ card, isPaymentRetry, invoiceId }) {
  // Set up payment method for recurring usage

  stripe
    .createPaymentMethod({
      type: 'card',
      card: card,
    })
    .then((result) => {
      if (result.error) {
        changeLoadingState(false);
        displayError(result);
      } else {
        if (isPaymentRetry) {
          // Update the payment method and retry invoice payment
          retryInvoiceWithNewPaymentMethod({
            paymentMethodId: result.paymentMethod.id,
            invoiceId: invoiceId,
            priceId: priceId,
          });
        } else {
          // Create the subscription
          createSubscription({
            paymentMethodId: result.paymentMethod.id,
            priceId: priceId,
          });
        }
      }
    });
}

function createSubscription({ paymentMethodId, priceId }) {
  return (
    fetch("{% url 'payment:create-subscription' %}", {
      method: 'post',
      headers: {
        'Content-Type': "application/json",
        'X-CSRFToken': csrftoken
      },
      body: JSON.stringify({
        paymentMethodId: paymentMethodId,
        priceId: priceId,
      }),
    })
      .then((response) => {
        return response.json();
      })
      // If the card is declined, display an error to the user.
      .then((result) => {
        if (result.error) {
          // The card had an error when trying to attach it to a customer.
          throw result;
        }
        return result;
      })
      // Normalize the result to contain the object returned by Stripe.
      // Add the additional details we need.
      .then((result) => {
        return {
          paymentMethodId: paymentMethodId,
          priceId: priceId,
          subscription: result,
        };
      })
      // Some payment methods require a customer to be on session
      // to complete the payment process. Check the status of the
      // payment intent to handle these actions.
      .then(handlePaymentThatRequiresCustomerAction)
      // If attaching this card to a Customer object succeeds,
      // but attempts to charge the customer fail, you
      // get a requires_payment_method error.
      .then(handleRequiresPaymentMethod)
      // No more actions required. Provision your service for the user.
      .then(onSubscriptionComplete)
      .catch((error) => {
        changeLoadingState(false);
        // An error has happened. Display the failure to the user here.
        // We utilize the HTML element we created.
        showCardError(error);
      })
  );
}

function handlePaymentThatRequiresCustomerAction({
  subscription,
  invoice,
  priceId,
  paymentMethodId,
  isRetry,
}) {
  if (subscription && subscription.status === 'active') {
    // Subscription is active, no customer actions required.
    return { subscription, priceId, paymentMethodId };
  }

  // If it's a first payment attempt, the payment intent is on the subscription latest invoice.
  // If it's a retry, the payment intent will be on the invoice itself.
  let paymentIntent = invoice ? invoice.payment_intent : subscription.latest_invoice.payment_intent;

  if (
    paymentIntent.status === 'requires_action' ||
    (isRetry === true && paymentIntent.status === 'requires_payment_method')
  ) {
    return stripe
      .confirmCardPayment(paymentIntent.client_secret, {
        payment_method: paymentMethodId,
      })
      .then((result) => {
        if (result.error) {
          // Start code flow to handle updating the payment details.
          // Display error message in your UI.
          // The card was declined (i.e. insufficient funds, card has expired, etc).
          throw result;
        } else {
          if (result.paymentIntent.status === 'succeeded') {
            // Show a success message to your customer.
            // There's a risk of the customer closing the window before the callback.
            // We recommend setting up webhook endpoints later in this guide.
            return {
              priceId: priceId,
              subscription: subscription,
              invoice: invoice,
              paymentMethodId: paymentMethodId,
            };
          }
        }
      })
      .catch((error) => {
        changeLoadingState(false);
        displayError(error);
      });
  } else {
    // No customer action needed.
    return { subscription, priceId, paymentMethodId };
  }
}

function handleRequiresPaymentMethod({
  subscription,
  paymentMethodId,
  priceId,
}) {
  if (subscription.status === 'active') {
    // subscription is active, no customer actions required.
    return { subscription, priceId, paymentMethodId };
  } else if (
    subscription.latest_invoice.payment_intent.status ===
    'requires_payment_method'
  ) {
    // Using localStorage to manage the state of the retry here,
    // feel free to replace with what you prefer.
    // Store the latest invoice ID and status.
    localStorage.setItem('latestInvoiceId', subscription.latest_invoice.id);
    localStorage.setItem(
      'latestInvoicePaymentIntentStatus',
      subscription.latest_invoice.payment_intent.status
    );
    throw { error: { message: 'Your card was declined.' } };
  } else {
    return { subscription, priceId, paymentMethodId };
  }
}

function onSubscriptionComplete(result) {
  // Payment was successful.
  if (result.subscription.status === 'active') {
      console.log("Complete")
      window.location.href = "{% url 'users:detail' request.user.username %}"
    // Change your UI to show a success message to your customer.
    // Call your backend to grant access to your service based on
    // `result.subscription.items.data[0].price.product` the customer subscribed to.
  }
}

function retryInvoiceWithNewPaymentMethod({
  paymentMethodId,
  invoiceId,
  priceId
}) {
  return (
    fetch("{% url 'payment:retry-invoice' %}", {
      method: 'post',
      headers: {
        'Content-Type': "application/json",
        'X-CSRFToken': csrftoken
      },
      body: JSON.stringify({
        paymentMethodId: paymentMethodId,
        invoiceId: invoiceId,
      }),
    })
      .then((response) => {
        return response.json();
      })
      // If the card is declined, display an error to the user.
      .then((result) => {
        if (result.error) {
          // The card had an error when trying to attach it to a customer.
          throw result;
        }
        return result;
      })
      // Normalize the result to contain the object returned by Stripe.
      // Add the additional details we need.
      .then((result) => {
        return {
          // Use the Stripe 'object' property on the
          // returned result to understand what object is returned.
          invoice: result,
          paymentMethodId: paymentMethodId,
          priceId: priceId,
          isRetry: true,
        };
      })
      // Some payment methods require a customer to be on session
      // to complete the payment process. Check the status of the
      // payment intent to handle these actions.
      .then(handlePaymentThatRequiresCustomerAction)
      // No more actions required. Provision your service for the user.
      .then(onSubscriptionComplete)
      .catch((error) => {
        changeLoadingState(false);
        // An error has happened. Display the failure to the user here.
        // We utilize the HTML element we created.
        displayError(error);
      })
  );
}

function changeLoadingState(isLoading) {
  if (isLoading) {
    document.querySelector('#button-text').classList.add('hidden');
    document.querySelector('#spinner').classList.remove('hidden');
    document.querySelector('#subscription-form button').disabled = true;
  } else {
    document.querySelector('#button-text').classList.remove('hidden');
    document.querySelector('#spinner').classList.add('hidden');
    document.querySelector('#subscription-form button').disabled = false;
  }
}

</script>

{% endblock javascript %}

templates/payment/enroll.html
{% extends "base.html" %}

{% block content %}

    <section class="text-gray-700 body-font overflow-hidden mt-24">
  <div class="container mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-yellow-500">Price</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base text-yellow-500">
        Web hosting
      </p>

    </div>
    <div class="flex flex-wrap justify-center -m-4">
            <div class="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div class="h-full p-6 rounded-lg border-2 border-yellow-300 flex flex-col relative overflow-hidden">
          <h2 class="text-sm tracking-widest title-font mb-1 font-medium">BASIC</h2>
          <h1 class="text-5xl text-purple-500 leading-none flex items-center pb-4 mb-4 border-b border-gray-200">
            <span>$22</span>
            <span class="text-lg ml-1 font-normal text-blue-500">/mo</span>
          </h1>
          <p class="flex items-center text-gray-300 mb-2">
            <span class="w-4 h-4 mr-2 inline-flex items-center justify-center bg-blue-500 text-white rounded-full flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" class="w-3 h-3" viewBox="0 0 24 24">
                <path d="M20 6L9 17l-5-5"></path>
              </svg>
            </span>Host with us
          </p>
          <p class="flex items-center text-blue-400 mb-2">
            <span class="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-500 text-white rounded-full flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" class="w-3 h-3" viewBox="0 0 24 24">
                <path d="M20 6L9 17l-5-5"></path>
              </svg>
            </span>Access to exclusive content
          </p>
              {% if request.user.is_authenticated %}
          <a href="{% url 'payment:payment' 'Econ' %}" class="flex items-center mt-auto text-white bg-green-600 border-0 py-2 px-4 w-full focus:outline-none hover:bg-purple-600 rounded">
            Enroll
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-auto" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
    {% else %}
    <a href="{% url 'account_signup' %}"
class="flex justify-center py-2 ml-1 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:border-green-700 focus:shadow-outline-green active:bg-green-700 transition duration-150 ease-in-out">
        Sign Up
     </a>
          <p class="text-xs text-gray-500 mt-3">Create an account or login!</p>

    {% endif %}
        </div>
      </div>
  </div>
      </div>
  </div>
</section>

{% endblock content %}